version: "3.9"

services:

  postgres:
    container_name: how-movie-db
    image: postgres
    environment:
      - POSTGRES_DB=hmdata
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5432:5432"
  django:
    container_name: how-movie-api
    build: 
      context: ./HowMovie_API/.
      dockerfile: ./Dockerfile
    volumes:
      - ./HowMovie_API/:/home/HowMovie_API
    working_dir: /home/HowMovie_API
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres
    command: >
      bash -c "
      chmod +x /wait-for-it.sh
      && /wait-for-it.sh postgres:5432 -t 10
      && python manage.py makemigrations API
      && python manage.py migrate API
      && python manage.py runserver 0.0.0.0:8000"
  spring:
    container_name: how-movie-login
    build:
      context: ./HowMovie_Login/oauth2/.
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"  
  next:
    container_name: how-movie-web
    build:
      context: ./HowMovie_Web/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
  