spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 7345dd34fad4c4b6e313b15506ac815b
            client-secret: caa05f990d5a2e85fde36f80d8d28afd
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Kakao
            scope:
#              - profile
              - profile_nickname
              - profile_image
              - account_email
          naver:
            client-id: LIuG6pm7RIP4MmDyhyvs
            client-secret: usou2qampP
            redirect-uri:  http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          google:
            client-id: 383902592347-eaqrov2grgu38re4trpjsf44mcspbasq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
 